tasks:
  - name: Start development environment
    init: |
      pnpm i
    command: |
      pnpm dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
    description: Website preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: prevent-merge-on-error
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
vscode:
  extensions:
    - christian-kohler.npm-intellisense
    - eamodio.gitlens
    - genuitecllc.codetogether
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - aaron-bond.better-comments
    - meganrogge.template-string-converter
    - leodevbro.blockman
    - Gruntfuggly.todo-tree
    - unifiedjs.vscode-mdx
    - bradlc.vscode-tailwindcss
    - PulkitGangwar.nextjs-snippets
    - PKief.material-icon-theme
